module.exports = {

  signup: require("./user/signup"),
  login: require("./user/login"),
  checkID: require("./user/checkID"),
  checkNickname: require("./user/checkNickname"),
  auth: require("./user/auth"),
  signupSMS: require("./user/signupSMS"),
  verify: require("./user/verify"),
  signupEmail: require("./user/signupEmail"),
  findID: require("./user/findID"),
  findPW: require("./user/findPW"),
  modify: require("./user/modify"),
  mypageCart: require("./user/mypageCart"),
  mypageLike: require("./user/mypageLike"),
  withdrawal: require("./user/withdrawal"),
  orderhistory: require("./user/orderhistory"),
  mypageOrderHistory: require("./user/mypageOrderHistory"),
  orderhistoryCancel: require("./user/orderhistoryCancel"),
  list: require("./product/list"),
  new: require("./product/new"),
  editor: require("./product/editor"),
  detail: require("./product/detail"),
  getLike: require("./product/getLike"),
  insertLike: require("./product/insertLike"),
  deleteLike: require("./product/deleteLike"),
  getCart: require("./product/getCart"),
  insertCart: require("./product/insertCart"),
  deleteCart: require("./product/deleteCart"),
  recommend: require("./product/recommend"),
  editGoods: require("./product/editGoods"),
  deleteGoods: require("./product/deleteGoods"),
  sellerList: require("./seller/sellerList")
  
};